# Generated by Django 4.1.1 on 2022-09-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homepagemodel_servicesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('days', models.CharField(max_length=255)),
                ('weekand', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='EmergencyModel',
        ),
        migrations.DeleteModel(
            name='HomepageModel',
        ),
        migrations.DeleteModel(
            name='HoursModel',
        ),
        migrations.DeleteModel(
            name='ServicesModel',
        ),
    ]
