# Generated by Django 4.1.1 on 2022-09-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_infomodel_delete_emergencymodel_delete_homepagemodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infomodel',
            old_name='days',
            new_name='emergancy',
        ),
        migrations.RenameField(
            model_name='infomodel',
            old_name='title',
            new_name='emergency_service',
        ),
        migrations.RenameField(
            model_name='infomodel',
            old_name='weekand',
            new_name='opening_hours',
        ),
        migrations.AddField(
            model_name='infomodel',
            name='location',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infomodel',
            name='opening_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infomodel',
            name='weekand_day',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infomodel',
            name='working_days',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infomodel',
            name='working_finish_time',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infomodel',
            name='working_hours',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infomodel',
            name='working_start_time',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infomodel',
            name='finish_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='infomodel',
            name='start_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
