# Generated by Django 4.1.1 on 2022-09-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_days_infomodel_emergancy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='services')),
                ('services_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
