# Generated by Django 4.1.1 on 2022-09-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ourservicesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutusblocModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_img', models.ImageField(upload_to='aboutus_blog')),
                ('block_title', models.CharField(max_length=255)),
                ('block_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_title', models.CharField(max_length=255)),
                ('phone_text', models.TextField()),
                ('phone_number', models.CharField(max_length=255)),
                ('email_title', models.CharField(max_length=255)),
                ('email_text', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('location_title', models.CharField(max_length=255)),
                ('location_text', models.TextField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_title', models.CharField(max_length=255)),
                ('telegram_link', models.CharField(max_length=300)),
                ('instagram_title', models.CharField(max_length=255)),
                ('instagram_link', models.CharField(max_length=300)),
            ],
        ),
    ]
