# Generated by Django 4.0.3 on 2022-09-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_aboutusblocmodel_contactmodel_linkmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomodel',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutusblocmodel',
            name='block_img',
            field=models.ImageField(upload_to='aboutus_blog/'),
        ),
        migrations.AlterField(
            model_name='ourservicesmodel',
            name='img',
            field=models.ImageField(upload_to='services/'),
        ),
    ]
