# Generated by Django 4.0.3 on 2022-09-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_infomodel_logo_alter_aboutusblocmodel_block_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomodel',
            name='emergency_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
