# Generated by Django 4.1.1 on 2022-09-08 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_infomodel_emergency_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='about_us_blog/')),
                ('title', models.CharField(max_length=255)),
                ('large_text', models.TextField()),
                ('small_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='blog/')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Bloglar',
            },
        ),
        migrations.CreateModel(
            name='Consulting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Doktorlar',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'About'), (2, 'Service'), (3, 'Doctor')])),
                ('savol', models.CharField(max_length=255)),
                ('javob', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='introduction/vid/')),
                ('large_text', models.TextField()),
                ('small_text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Introduction',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Top'), (2, 'Normal')])),
                ('img', models.ImageField(upload_to='news/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='service/')),
                ('banner_img', models.ImageField(upload_to='service/')),
                ('small_title', models.CharField(max_length=255)),
                ('large_title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('large_text', models.TextField()),
                ('banner', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Servislar',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Operationg_Attented',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='operation/img/')),
                ('video', models.FileField(upload_to='operation/vid/')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('project_detail', models.TextField()),
                ('project_detail_img', models.ImageField(blank=True, null=True, upload_to='operation/img/')),
                ('video_under_text', models.TextField()),
                ('participating_doctors', models.ManyToManyField(to='main.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='Doctors_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctors')),
                ('operations', models.ManyToManyField(to='main.operationg_attented')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.doctors')),
            ],
        ),
    ]
