# Generated by Django 4.1.1 on 2022-09-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_aboutus_blog_aboutus_block_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors_detail',
            new_name='Doctors_about',
        ),
        migrations.DeleteModel(
            name='AboutusblockModel',
        ),
        migrations.DeleteModel(
            name='ContactModel',
        ),
        migrations.DeleteModel(
            name='LinkModel',
        ),
        migrations.DeleteModel(
            name='OurServicesModel',
        ),
        migrations.RenameField(
            model_name='infomodel',
            old_name='emergancy',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='infomodel',
            old_name='finish_time',
            new_name='weekend_days',
        ),
        migrations.RenameField(
            model_name='infomodel',
            old_name='start_time',
            new_name='weekend_time',
        ),
        migrations.RenameField(
            model_name='infomodel',
            old_name='emergency_number',
            new_name='working_time',
        ),
        migrations.RemoveField(
            model_name='infomodel',
            name='emergency_service',
        ),
        migrations.RemoveField(
            model_name='infomodel',
            name='number',
        ),
        migrations.RemoveField(
            model_name='infomodel',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='infomodel',
            name='opening_text',
        ),
        migrations.RemoveField(
            model_name='infomodel',
            name='text',
        ),
        migrations.RemoveField(
            model_name='infomodel',
            name='weekand_day',
        ),
        migrations.RemoveField(
            model_name='infomodel',
            name='working_finish_time',
        ),
        migrations.RemoveField(
            model_name='infomodel',
            name='working_hours',
        ),
        migrations.RemoveField(
            model_name='infomodel',
            name='working_start_time',
        ),
        migrations.AddField(
            model_name='infomodel',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infomodel',
            name='instagram_link',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infomodel',
            name='telegram_link',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
