# Generated by Django 4.1.1 on 2022-09-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_operationg_attented_main_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationg_attented',
            name='main_doctor',
        ),
    ]
