# Generated by Django 4.0.6 on 2022-09-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_doctors_about_operations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aboutus_block',
            new_name='Aboutus_blog',
        ),
        migrations.AlterField(
            model_name='doctors_about',
            name='operations',
            field=models.ManyToManyField(blank=True, null=True, to='main.operationg_attented'),
        ),
    ]
