# Generated by Django 4.0.6 on 2022-09-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_doctors_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservice',
            name='banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='service/'),
        ),
    ]
