# Generated by Django 4.0.6 on 2022-09-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_ourservice_banner_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='img',
            field=models.ImageField(default=1, upload_to='doctors/img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctors',
            name='bio',
            field=models.CharField(max_length=300),
        ),
    ]
